### ISSUE TITLE
installation isn't working

### ISSUE THREAD

**Issue by mrT23** [kakaobrain/torchlars#2]
I tried to install the package via 'pip install torchlars' and got an empty directory of torchlars (0.0.0)

I clone the repo and ran manually:  'python setup.py install'. I got a compilation error:

```
1 error detected in the compilation of 1 error detected in the compilation of "C:/Users/echlon/AppData/Local/Temp/tmpxft_00000f94_00000000-10_adaptive_lr_cuda.cpp1.ii".
error: command 'C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v10.0\\bin\\nvcc.exe' failed with exit status 1
```

i have pytorch 1.2 and python 3.7 on windows.

**Comment by sublee** [comment]
Sorry for your inconvenience. Currently, we don't have a plan to support Windows.

**Comment by mrT23** [comment]
ok, tried it on linux.
still, the PIP install brings version 0.0.0, which is empty

"Collecting torchlars (from -r requirements.txt (line 13))
  Downloading http://mirrors.aliyun.com/pypi/packages/d4/1d/cbbd3be0ff8a284c87dc167fbe248f96781f75be9cf10fa3fc3a865918c2/torchlars-0.0.0.tar.gz"
...
    from torchlars import LARS
ImportError: cannot import name 'LARS'

**Comment by cmpark0126** [comment]
We have uploaded new version of torchlars on PyPi two hours ago.
So, could you please uninstall past version and install new version 0.1.0 torchlars again?

If the same problem occurs after you download the new version, please let us know again.

Thank you.

**Comment by mrT23** [comment]
thanks for the support guys, it now works :)

I was able to train Resnet with batch size of ~40,000 with SGD to 76% (lr==12).
I am curious to see if LARS can give an improvement in terms of accuracy/run-time

good job on the package.

**Comment by cmpark0126** [comment]
I think you can obtain a better result in terms of acc/run-time if you use large batch size with LARS.
Don't forget using warm-up when you train your model, and adjusting the initial learning rate according to batch size which you plan to use. ;)

Thank you for using `torchlars`, and I hope you get the results you want.

**Comment by cmpark0126** [comment]
@mrT23 Since you have solved your problem, I'm going to close this issue. Feel free to reopen it if you have further questions or comments about this issue. :)

**Comment by WOWNICE** [comment]
I failed intalling the package as the following error message. btw, does this implementation skip 'bn' layer and 'bias' layer? as suggested here: https://github.com/pytorch/pytorch/issues/18414
 
 RuntimeError: Error compiling objects for extension
  ----------------------------------------
  ERROR: Failed building wheel for torchlars
