### ISSUE TITLE
compute_adaptive_lr not defined

### ISSUE THREAD

**Issue by Jihoon-Tack** [kakaobrain/torchlars#6]
Hi,

While using your torchlars package with installing with pip, an error occurred as follows:
NameError: name 'compute_adaptive_lr' is not defined

Currently using torch 1.1.0, python 3.6.9, CUDA 10.1

Thank you

**Comment by sublee** [comment]
Thank you for reporting the installation problem. There was a mistake on the last distribution. I've just fixed the problem. You will be able to install torchlars-0.1.2 with valid `compute_adaptive_lr`. If you still have the problem, please reopen this issue.

**Comment by DeppMeng** [comment]
I still has this issue. torch 1.3 python 3.6.3 CUDA 10.0

Error message:
from torchlars.lars import LARS
  File "/opt/conda/envs/moco-python3.6.3/lib/python3.6/site-packages/torchlars/lars.py", line 6, in <module>
    from torchlars._adaptive_lr import compute_adaptive_lr
ImportError: /opt/conda/envs/moco-python3.6.3/lib/python3.6/site-packages/torchlars/_adaptive_lr.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZN3c1011CPUTensorIdEv

Thanks

**Comment by sublee** [comment]
@DeppMeng I don't reproduce your error. But I found a similar issue: https://github.com/NVIDIAGameWorks/kaolin/issues/30. Maybe reinstalling `torch` and `torchlars` could fix your error.
